---
title: "---
title: "FINM7406 Semester 1 2022"
author: "Yiyi"
date: "`r Sys.Date()`"
output:
  bookdown::pdf_document2:
    toc: yes
  header-includes:
  - \usepackage{placeins}
  - \usepackage{multirow}
  - \usepackage{multicolumn}
  - \usepackage{caption}
  - \usepackage[absolute,overlay]{textpos}
  - \usepackage{float}
  - \usepackage{graphicx}
  - \usepackage{booktabs}
  html_document:
    toc: yes
    df_print: paged
  word_document: default

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r rm, include=FALSE}
 rm(list = ls())
Sys.setlocale("LC_TIME", "English")
```

```{r Library, include=FALSE}
#Packages
library(readxl)
library(data.table)
library(lubridate)#extract cpi time to newdata(furniture48)
library(tidyverse) 
library(broom)
library(stargazer)
library(knitr)
library(officer)
library(flextable)
library(magrittr)
library(dplyr)
library(moments)
library(Inflation)
library(ggplot2)
library(zoo)
library(xts)
library(hydroTSM)
library(openair)
library(tibble)
library(miscTools)
library(priceR)
library(Metrics)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(kableExtra)
library(gridExtra)
library(egg)
library(grid)
library(cowplot)
library(spatstat)#shift有重复
library(SciViews)
library(sos)
library(nowcasting)
```

```{r language,message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
Sys.setlocale("LC_TIME","English")
```

```{r}
#read data
df1<-readxl:: read_xlsx("usdeur(part2).xlsx",1)
#convert to quarterly
df1$Date<-as.Date(df1$date,format="%d-%b-%Y")
dd<-arrange(df1,Date)
dd$qdate<-as.yearqtr(dd$Date)
dd<-dd %>%
  group_by(qdate) %>%
  summarise_all(mean)
```


```{r}
spotmid71<-lead(dd$spotmid)
spotmid71<-spotmid71[-72]
forward71<-dd$`forward mid rate`[-72]
res<-lm(spotmid71~forward71)
summary(res)
stargazer(res,type="text")
```


```{r}
library(openxlsx)
#write.xlsx(dd,"data_qtrly.xlsx")
#first regression
diff_st<-diff(dd$spotmid)
diff_f_s<-dd$`forward mid rate`-dd$spotmid
diff_f_s<-diff_f_s[-72]
#regression

regression1<-lm(diff_st~diff_f_s)
```

```{r}
lm(~log(diff_f_s))
```


```{r}
summary(regression1)
#log-linearized
log_dd<-log(dd[,c(3,5)])
colnames(log_dd)<-c("log_spot_mid_rates(return)","log_forward_mid_rates(premium/discount)")
#log s t+1
log_s_t_diff<-diff(log_dd$`log_spot_mid_rates(return)`)
log_diff_ft_st<-log_dd$`log_forward_mid_rates(premium/discount)`- log_dd$`log_spot_mid_rates(return)`
log_diff_ft_st<-log_diff_ft_st[-72]
#regression
  regression<-lm(log_s_t_diff~log_diff_ft_st)

stargazer(regression,
          type = "text")
summary(regression)
```


```{r}
t.test(spotmid71,forward71)
```



```{r}
t.test(log_s_t_diff,log_diff_ft_st)
```

