---
title: "Quarterly Stepwise Output"
author: "Yiyi"
date: "`r Sys.Date()`"
output:
  html_document:
    highlight: tango
    number_sections: yes
    theme: united
    toc: yes
    toc_depth: 3
  pdf_document:
    toc: yes
    toc_depth: '3'
---
# 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
 rm(list = ls())
Sys.setlocale("LC_TIME", "English")
```
## Packages
```{r Library, include=FALSE}
library(readxl)
library(data.table)
library(lubridate)#extract cpi time to newdata(furniture48)
library(dplyr) 
library(tidyverse) 
library(broom)
library(stargazer)
library(knitr)
library(officer)
library(flextable)
library(magrittr)
library(dplyr)
```

```{r}
rm(list = ls())
Sys.setlocale("LC_TIME", "English")
```

```{r}
cpi <- read_excel("correct quarter cpi.xlsx")#108
cols.num <- c(colnames(cpi))#cols.列名
cpi[cols.num] <- sapply(cpi[cols.num],as.numeric)#把所有数据转成数字类型?

cpi <- as.data.table(cpi)
colnames(cpi) = gsub("&", "and", colnames(cpi))#把列名里&换成 and
COPY<-copy(cpi)
tracemem(COPY)==tracemem(cpi)
Data_A = as.data.table (cpi)

Varnames <- copy(names(Data_A))#
Data_A[, (names(Data_A)) := lapply(.SD, as.numeric)][,
                                                     rn := .I]
melted <- melt(Data_A, id.vars="rn")[,
                                     (paste0("lag_", 0:4)) := shift(value, 0:4, type="lag"),
                                     by=variable][, 
                                                  value:=NULL][]
res <- dcast.data.table(melt(melted, id.vars=c("rn", "variable"), variable.name="lag"),
                        rn ~ variable + lag, sum)
res[, ncol(res), with=FALSE]
cpi <- cpi[, unlist(lapply(.SD, shift, n = 0:4), recursive = FALSE)]#lags generation
# quarterly  Dummies ---------------------------------------------------------


cpi$time <- seq.Date(from = as.Date("1992/01/01",format = "%Y/%m/%d"), by = "quarter", length.out = 112)
cpi$time <- format(cpi$time, format = "%b")

cpi <- fastDummies::dummy_cols(cpi, select_columns = "time", remove_most_frequent_dummy = TRUE,
)

cpi$time1 <- seq.Date(from = as.Date("1992/01/01",format = "%Y/%m/%d"), by = "quarter", length.out = 112)
# Trend,vat, recession ----------------------------------------------------

newdata<-copy(cpi)

newdata<-newdata[newdata$'time1' >= as.Date("1993-01-01")]
Trend <- seq_along(newdata$time1)

VAT1 <- as.numeric(newdata$`time1` == "2008-10-01")
VAT2 <- as.numeric(newdata$`time1` == "2010-01-01")
VAT3 <- as.numeric(newdata$`time1` == "2011-01-01")
Recession <- as.numeric(newdata$`time1` >= "2008-04-01" & newdata$`time1`<= "2009-06-01")
# Lag ---------------------------------------------------------------------

lag1 <- newdata %>% 
  select(matches("(2)$"))
lag2 <- newdata %>% 
  select(matches("(3)$"))
lag3 <- newdata %>% 
  select(matches("(4)$"))
lag4 <- newdata %>% 
  select(matches("(5)$"))

# quarterly DUMMIES --------------------------------------------------------


quarter1 <- as.numeric(newdata$time_Jan)
quarter3 <- as.numeric(newdata$time_Jul)
quarter4 <- as.numeric(newdata$time_Oct)

COPY <- as.data.frame(COPY)
lag1 <- as.data.frame(lag1)
lag2 <- as.data.frame(lag2)
lag3 <- as.data.frame(lag3)
lag4 <- as.data.frame(lag4)

# CPI-LAGS ----------------------------------------------------------------


CPI_lag1 <- (newdata$"CPI ALL ITEMS2")
CPI_lag2 <- (newdata$"CPI ALL ITEMS3")
CPI_lag3 <- (newdata$"CPI ALL ITEMS4")
CPI_lag4 <- (newdata$"CPI ALL ITEMS5")

```

```{r}
# Copy删除前四行,因为copy是从1992年开始的,只是了生成lag所以才保存1992年开始,用完了可以删了. --------------------------------------------------

COPY<-COPY[-1:-4,]
```
## Regression
```{r}
CPI.model <- lapply(1, function(x) lm(COPY[,x] ~ lag1[,x]+lag2[,x]+lag3[,x]+lag4[,x]+ quarter1+quarter3+quarter4+VAT1+VAT2+VAT3+Recession+Trend)
)

for (i in 1) {
  names(CPI.model[[i]]$coefficients)<-c('Constant','lag1','lag2',"lag3","lag4",
                                         "quarter1","quarter3","quarter4",
                                         "VAT1","VAT2","VAT3","Recession","Trend")
}

regression <- lapply(1:122, function(x) lm(COPY[,x] ~ lag1[,x]+lag2[,x]+lag3[,x]+lag4[,x]+CPI_lag1+CPI_lag2+CPI_lag3+CPI_lag4+ quarter1+quarter3+quarter4+VAT1+VAT2+VAT3+Recession+Trend)
)
for (i in 1:122) {
  names(regression[[i]]$coefficients)<-c('Constant','lag1','lag2',"lag3","lag4",
                                         "CPI_lag1","CPI_lag2","CPI_lag3","CPI_lag4",
                                         "quarter1","quarter3","quarter4",
                                         "VAT1","VAT2","VAT3","Recession","Trend")
}
```

# quarterly stepwise

## stepwise function
```{r include=FALSE}
# function ----------------------------------------------------------------


# Automated model selection
# Author      : Joris Meys
# version     : 0.2
# date        : 12/01/09

#CHANGE LOG
# 0.2   : check for empty scopevar vector

# #CHANGE LOG -------------------------------------------------------------



# Function has.interaction checks whether x is part of a term in terms
# terms is a vector with names of terms from a model
has.interaction <- function(x,terms){
  out <- sapply(terms,function(i){
    sum(1-(strsplit(x,":")[[1]] %in% strsplit(i,":")[[1]]))==0
  })
  return(sum(out)>0)
}

# Function Model.select
# model is the lm object of the full model
# keep is a list of model terms to keep in the model at all times
# sig gives the significance for removal of a variable. Can be 0.1 too (see SPSS)
# verbose=T gives the F-tests, dropped var and resulting model after 
model.select <- function(model,keep,sig=0.05,verbose=F){
  counter=1
  # check input
  if(!is(model,"lm")) stop(paste(deparse(substitute(model)),"is not an lm object\n"))
  # calculate scope for drop1 function
  terms <- attr(model$terms,"term.labels")
  if(missing(keep)){ # set scopevars to all terms
    scopevars <- terms
  } else{            # select the scopevars if keep is used
    index <- match(keep,terms)
    # check if all is specified correctly
    if(sum(is.na(index))>0){
      novar <- keep[is.na(index)]
      warning(paste(
        c(novar,"cannot be found in the model",
          "\nThese terms are ignored in the model selection."),
        collapse=" "))
      index <- as.vector(na.omit(index))
    }
    scopevars <- terms[-index]
  }
  
  # Backward model selection : 
  
  while(T){
    # extract the test statistics from drop.
    test <- drop1(model, scope=scopevars,test="F")
    
    if(verbose){
      cat("-------------STEP ",counter,"-------------\n",
          "The drop statistics : \n")
      print(test)
    }
    
    pval <- test[,dim(test)[2]]
    
    names(pval) <- rownames(test)
    pval <- sort(pval,decreasing=T)
    
    if(sum(is.na(pval))>0) stop(paste("Model",
                                      deparse(substitute(model)),"is invalid. Check if all coefficients are estimated."))
    
    # check if all significant
    if(pval[1]<sig) break # stops the loop if all remaining vars are sign.
    
    # select var to drop
    i=1
    while(T){
      dropvar <- names(pval)[i]
      check.terms <- terms[-match(dropvar,terms)]
      x <- has.interaction(dropvar,check.terms)
      if(x){i=i+1;next} else {break}              
    } # end while(T) drop var
    
    if(pval[i]<sig) break # stops the loop if var to remove is significant
    
    if(verbose){
      cat("\n--------\nTerm dropped in step",counter,":",dropvar,"\n--------\n\n")              
    }
    
    #update terms, scopevars and model
    scopevars <- scopevars[-match(dropvar,scopevars)]
    terms <- terms[-match(dropvar,terms)]
    
    formul <- as.formula(paste(".~.-",dropvar))
    model <- update(model,formul)
    
    if(length(scopevars)==0) {
      warning("All variables are thrown out of the model.\n",
              "No model could be specified.")
      return()
    }
    counter=counter+1
  } # end while(T) main loop
  return(model)
}

```

```{r }
slr.total <- list()
keep.dummies <- c("quarter1","quarter3","quarter4",
                  "VAT1","VAT2","VAT3","Recession","Trend")
for (i in 2: length(regression)) {
  slr.total[[i]] <- model.select(regression[[i]], keep = keep.dummies, sig = 0.05, verbose = F)
}

CPI_ <- CPI.model[[1]]
slr.cpi <- model.select(CPI_,keep = keep.dummies,sig = 0.05,verbose = F)

```
## 空集部分
```{r}
names(slr.total) <- 1:length(slr.total)
class_with_no_significant <- slr.total[which(sapply(slr.total, is.null))]
class_with_no_significant<-as.numeric(names(class_with_no_significant))
length(class_with_no_significant)
```

```{r}
slr.total[sapply(slr.total, is.null)] <- NULL

```

```{r}

search_for_these <- c("lag1[, x]","lag2[, x]","lag3[, x]","lag4[, x]","lag5[, x]","lag6[, x]","lag7[, x]","lag8[, x]","lag9[, x]","lag10[, x]","lag11[, x]","lag12[, x]")
 replace_with_these <- c("lag1","lag2","lag3","lag4","lag5","lag6","lag7","lag8","lag9","lag10","lag11","lag12")
```

## 会卡2下
```{r}

found<-list()
for (i in 1:length(slr.total )) {
  found[[i]] <- match(names(slr.total[[i]]$coefficients), search_for_these, nomatch = 0)
  names(slr.total[[i]]$coefficients)[names(slr.total[[i]]$coefficients) %in% search_for_these] <- replace_with_these[found[[i]]]
}
```

```{r}
found<-list()
for (i in 1:length(slr.cpi )) {
  found[[i]] <- match(names(slr.cpi$coefficients), search_for_these, nomatch = 0)
  names(slr.cpi$coefficients)[names(slr.cpi$coefficients) %in% search_for_these] <- replace_with_these[found[[i]]]
}
```

## 12 divisions output
```{r}
vars.order<-c("lag1","lag2","lag3","lag4","lag5","lag6","lag7","lag8","lag9","lag10","lag11","lag12","CPI_lag1","CPI_lag2","CPI_lag3","CPI_lag4","CPI_lag5","CPI_lag6","CPI_lag7",
                                             "CPI_lag8","CPI_lag9",
                                             "CPI_lag10","CPI_lag11","CPI_lag12")

div.122.poi<-c(2, 16, 22, 28 ,41,  54,  62, 77, 80,  102, 103, 108)

division.name<-colnames(COPY[,div.122.poi])

without.17na<-subset(COPY,select = -c((class_with_no_significant)))

na.name<-colnames(COPY)[class_with_no_significant]

idx=which(division.name %in% na.name)
division.name=division.name[-idx]
div.poi.test<-vector()
for (i in 1:length(division.name)) {
  div.poi.test[i]<-which(colnames(without.17na)==division.name[i])
  
}

length(div.poi.test)

```

```{r}


div.name<-c("CPI","01FB", "02AT", "03CF", "04HW", "05FH", "06HL", "07TR", "08CM", "09RC", "10ED" , "12MS")



stargazer(slr.cpi,slr.total[div.poi.test],
          star.char = c("*"),
          star.cutoffs = c(0.01),
          notes = c(" * p<0.01; "),
           omit = c("quarter1","quarter3","quarter4",
                   "VAT1","VAT2","VAT3","Recession","Trend",'Constant'),
          order=paste0("^", vars.order , "$"),
          dep.var.labels.include = FALSE,
          notes.append = FALSE,

          report = "vc*",
          align = TRUE,
          header = FALSE,
          df = FALSE,
          digits = 2, single.row = TRUE,
          model.numbers = FALSE,
          column.labels = c(div.name),
          summary = FALSE,
          out = "F:/R workspace/Modelling-UK-inflation-quarterly-/Quarterly-divisions.html",
          
          se = NULL,type = "html"
)
```

## Groups
```{r}
groups.name <- read_excel("groups name.xlsx")
colnames(groups.name) = gsub("&", "and", colnames(groups.name))
groups.name<-colnames(groups.name)
na.name<-colnames(COPY)[class_with_no_significant]
#groups 里h有 na.name 没有的
na.groups<-intersect(na.name,groups.name)

idx=which(groups.name %in% na.name)
groups.name=groups.name[-idx]
groups.poi.test<-vector()
for (i in 1:length(groups.name)) {
  groups.poi.test[i]<-which(colnames(without.17na)==groups.name[i])
  
}




groups.poi<-c(2,12,16,20,22,26,28,29,32,35,41,44,45,48,49,50,54,57,60,62,66,71,77,78,80,85,87,92,95,99,102,105,107,110,113,114,118,120)
shabi<-list(groups.poi,groups.poi.test)
sapply(shabi,length)

```

### stargazer
```{r}
stargazer(slr.total[groups.poi.test[1:8]],
          star.char = c("*"),
          star.cutoffs = c(0.01),
          notes = c(" * p<0.01; "),
           omit = c("quarter1","quarter3","quarter4",
                   "VAT1","VAT2","VAT3","Recession","Trend",'Constant'),
          order=paste0("^", vars.order , "$"),
          dep.var.labels.include = FALSE,
          notes.append = FALSE,

          report = "vc*",
          align = TRUE,
          header = FALSE,
          df = FALSE,
          digits = 2, single.row = TRUE,
          model.numbers = FALSE,
          column.labels = c(groups.name[1:8]),
          summary = FALSE,
          out = "F:/R workspace/Modelling-UK-inflation-quarterly-/Quarterly-groups1.html",
          
          se = NULL,type = "html"
)
#---

stargazer(slr.total[groups.poi.test[9:16]],
          star.char = c("*"),
          star.cutoffs = c(0.01),
          notes = c(" * p<0.01; "),
           omit = c("quarter1","quarter3","quarter4",
                   "VAT1","VAT2","VAT3","Recession","Trend",'Constant'),
          order=paste0("^", vars.order , "$"),
          dep.var.labels.include = FALSE,
          notes.append = FALSE,

          report = "vc*",
          align = TRUE,
          header = FALSE,
          df = FALSE,
          digits = 2, single.row = TRUE,
          model.numbers = FALSE,
          column.labels = c(groups.name[9:16]),
          summary = FALSE,
          out = "F:/R workspace/Modelling-UK-inflation-quarterly-/Quarterly-groups2.html",
          
          se = NULL,type = "html"
)

stargazer(slr.total[groups.poi.test[17:24]],
          star.char = c("*"),
          star.cutoffs = c(0.01),
          notes = c(" * p<0.01; "),
           omit = c("quarter1","quarter3","quarter4",
                   "VAT1","VAT2","VAT3","Recession","Trend",'Constant'),
          order=paste0("^", vars.order , "$"),
          dep.var.labels.include = FALSE,
          notes.append = FALSE,

          report = "vc*",
          align = TRUE,
          header = FALSE,
          df = FALSE,
          digits = 2, single.row = TRUE,
          model.numbers = FALSE,
          column.labels = c(groups.name[17:24]),
          summary = FALSE,
          out = "F:/R workspace/Modelling-UK-inflation-quarterly-/Quarterly-groups3.html",
          
          se = NULL,type = "html"
)

stargazer(slr.total[groups.poi.test[25:34]],
          star.char = c("*"),
          star.cutoffs = c(0.01),
          notes = c(" * p<0.01; "),
           omit = c("quarter1","quarter3","quarter4",
                   "VAT1","VAT2","VAT3","Recession","Trend",'Constant'),
          order=paste0("^", vars.order , "$"),
          dep.var.labels.include = FALSE,
          notes.append = FALSE,

          report = "vc*",
          align = TRUE,
          header = FALSE,
          df = FALSE,
          digits = 2, single.row = TRUE,
          model.numbers = FALSE,
          column.labels = c(groups.name[25:34]),
          summary = FALSE,
          out = "F:/R workspace/Modelling-UK-inflation-quarterly-/Quarterly-groups4.html",
          
          se = NULL,type = "html"
)
```


