#Packages
library(readxl)
library(data.table)
library(lubridate)#extract cpi time to newdata(furniture48)
library(scales)
library(tidyverse)
library(broom)
library(stargazer)
library(knitr)
library(officer)
library(flextable)
library(magrittr)
library(dplyr)
library(moments)
library(Inflation)
library(ggplot2)
library(zoo)
library(xts)
library(hydroTSM)
library(openair)
library(tibble)
library(miscTools)
library(priceR)
library(Metrics)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(kableExtra)
library(gridExtra)
library(egg)
library(grid)
library(cowplot)
library(spatstat)#shift有重复
library(SciViews)
library(sos)
library(parallel)
library(benchmarkme)
library(predict3d)
library(interactions)
library(aTSA)
library(tseries)
library(forecast)
library(officer)
library(tidyverse)
library(rvg)
library(equatiomatic)
options(scipen = 200)

rm(list = ls())
'%!in%' <- function(x, y)
        ! ('%in%'(x, slack))

# -------------------------------------------------------------------------
# 
 TM<-fread("Trimmead mean/Trimmed mean.csv")

TMM<- TM[which(TM[,1]=="2005m1"):which(TM[,1]=="2019m12"),]

